ignoreFiles:
  - node_modules/**/*

defaultSeverity: warning

plugins:
  - stylelint-scss
  - stylelint-order

rules:

  # Specify a blacklist of disallowed at-rules.
  at-rule-blacklist:
    - debug

  # Require or disallow an empty line before at-rules.
  at-rule-empty-line-before:
    - always
    -
      except:
        - blockless-after-blockless
        - first-nested
      ignore:
        - after-comment
      ignoreAtRules:
        - else

  # Specify lowercase or uppercase for at-rules names.
  at-rule-name-case: lower

  # Require a newline after at-rule names.
  at-rule-name-newline-after: always-multi-line

  # Require a single space after at-rule names.
  at-rule-name-space-after: always

  # Disallow vendor prefixes for at-rules.
  at-rule-no-vendor-prefix: true

  # Require a newline after the semicolon of at-rules.
  at-rule-semicolon-newline-after: always

  # Require a single space or disallow whitespace before the semicolons of at rules.
  at-rule-semicolon-space-before: never

  # Require or disallow an empty line before the closing brace of blocks.
  block-closing-brace-empty-line-before: never

  # Require a newline or disallow whitespace after the closing brace of blocks.
  block-closing-brace-newline-after: always

  # Require a newline or disallow whitespace before the closing brace of blocks.
  block-closing-brace-newline-before: always-multi-line

  # Require a single space or disallow whitespace before the closing brace of blocks.
  block-closing-brace-space-before: always-single-line

  # Disallow empty blocks.
  block-no-empty: true

  # equire a newline after the opening brace of blocks.
  block-opening-brace-newline-after: always-multi-line

  # Require a single space or disallow whitespace after the opening brace of blocks.
  block-opening-brace-space-after: always-single-line

  # Require a single space or disallow whitespace before the opening brace of blocks.
  block-opening-brace-space-before: always

  # Specify lowercase or uppercase for hexadecimal color values.
  color-hex-case: lower

  # Specify short or long notation for hexadecimal color values.
  color-hex-length: long

  # Disallow invalid hexadecimal colors.
  color-no-invalid-hex: true

  # Require (where possible) or disallow named colors.
  color-named: never

  # Disallow empty comments.
  comment-no-empty: true

  # Require or disallow whitespace on the inside of comment markers.
  comment-whitespace-inside: always

  # Require or disallow an empty line before custom properties (Autofixable).
  custom-property-empty-line-before: never

  # Require a single space or disallow whitespace after the bang of declarations.
  declaration-bang-space-after: never

  # Require a single space or disallow whitespace before the bang of declarations.
  declaration-bang-space-before: always

  # Disallow duplicate properties within declaration blocks.
  declaration-block-no-duplicate-properties: true

  # Disallow longhand properties that can be combined into one shorthand property.
  declaration-block-no-redundant-longhand-properties: true

  # Disallow shorthand properties that override related longhand properties.
  declaration-block-no-shorthand-property-overrides: true

  # Limit the number of declaration within single line declaration blocks.
  declaration-block-single-line-max-declarations: 1

  # Require a newline or disallow whitespace after the semicolons of declaration blocks.
  declaration-block-semicolon-newline-after: always-multi-line

  # Require a newline or disallow whitespace before the semicolons of declaration blocks.
  declaration-block-semicolon-newline-before: never-multi-line

  # Require a single space or disallow whitespace after the semicolons of declaration blocks.
  declaration-block-semicolon-space-after: always-single-line

  # Require a single space or disallow whitespace before the semicolons of declaration blocks.
  declaration-block-semicolon-space-before: never

  # Require or disallow a trailing semicolon within declaration blocks.
  declaration-block-trailing-semicolon: always

  # Require a newline or disallow whitespace after the colon of declarations.
  declaration-colon-newline-after: always-multi-line

  # Require a single space or disallow whitespace after the colon of declarations.
  declaration-colon-space-after: always-single-line

  # Require a single space or disallow whitespace before the colon of declarations.
  declaration-colon-space-before: never

  # Specify whether or not quotation marks should be used around font family names.
  font-family-name-quotes: always-where-recommended

  # Disallow duplicate font family names.
  font-family-no-duplicate-names: true

  # Require numeric or named (where possible) `font-weight` values.
  font-weight-notation: named-where-possible

  # Disallow an unspaced operator within `calc` functions.
  function-calc-no-unspaced-operator: true

  # Require a newline or disallow whitespace after the commas of functions.
  function-comma-newline-after: always-multi-line

  # Require a newline or disallow whitespace before the commas of functions.
  function-comma-newline-before: never-multi-line

  # Require a single space or disallow whitespace after the commas of functions.
  function-comma-space-after: always-single-line

  # Require a single space or disallow whitespace before the commas of functions.
  function-comma-space-before: never

  # Disallow direction values in `linear-gradient()` calls that are not valid.
  function-linear-gradient-no-nonstandard-direction: true

  # Limit the number of adjacent empty lines within functions.
  function-max-empty-lines: 0

  # Specify lowercase or uppercase for function names.
  function-name-case: lower

  # Require a newline or disallow whitespace on the inside of the parentheses of functions.
  function-parentheses-newline-inside: always-multi-line

  # Require a single space or disallow whitespace on the inside of the parentheses of functions.
  function-parentheses-space-inside: never-single-line

  # Disallow scheme-relative URLs.
  function-url-no-scheme-relative: true

  # Require or disallow quotes for URLs.
  function-url-quotes: always

  # Require or disallow whitespace after functions.
  function-whitespace-after: always

  # Specify indentation.
  indentation: 4

  # Disallow `!important` within keyframe declarations.
  keyframe-declaration-no-important: true

  # Disallow units for zero lengths.
  length-zero-no-unit: true

  # Limit the number of adjacent empty lines.
  max-empty-lines: 3

  # Limit the depth of nesting.
  max-nesting-depth: 4

  # Require a single space or disallow whitespace after the colon in media features.
  media-feature-colon-space-after: always

  # Require a single space or disallow whitespace before the colon in media features.
  media-feature-colon-space-before: never

  # Specify lowercase or uppercase for media feature names.
  media-feature-name-case: lower

  # Disallow unknown media feature names.
  media-feature-name-no-unknown: true

  # Disallow vendor prefixes for media feature names.
  media-feature-name-no-vendor-prefix: true

  # Require a single space or disallow whitespace on the inside of the parentheses within media features.
  media-feature-parentheses-space-inside: never

  # Require a single space or disallow whitespace after the range operator in media features.
  media-feature-range-operator-space-after: always

  # Require a single space or disallow whitespace before the range operator in media features.
  media-feature-range-operator-space-before: always

  # Require a newline or disallow whitespace after the commas of media query lists.
  media-query-list-comma-newline-after: never-multi-line

  # Require a newline or disallow whitespace before the commas of media query lists.
  media-query-list-comma-newline-before: never-multi-line

  # Require a single space or disallow whitespace after the commas of media query lists.
  media-query-list-comma-space-after: always

  # Require a single space or disallow whitespace before the commas of media query lists.
  media-query-list-comma-space-before: never

  # Disallow duplicate `@import` rules within a stylesheet.
  no-duplicate-at-import-rules: true

  # Disallow empty sources.
  no-empty-source: true

  # Disallow end-of-line whitespace.
  no-eol-whitespace: true

  # Disallow extra semicolons.
  no-extra-semicolons: true

  # Disallow double-slash comments (`//`) which are not supported by CSS.
  no-invalid-double-slash-comments: true

  # Disallow missing end-of-source newlines.
  no-missing-end-of-source-newline: true

  # Require or disallow a leading zero for fractional numbers less than 1.
  number-leading-zero: always

  # Limit the number of decimal places allowed in numbers.
  number-max-precision: 7

  # Disallow trailing zeros in numbers.
  number-no-trailing-zeros: true

  # Specify lowercase or uppercase for properties.
  property-case: lower

  # Disallow unknown properties.
  property-no-unknown: true

  # Require a single space or disallow whitespace on the inside of the brackets within attribute selectors.
  selector-attribute-brackets-space-inside: never

  # Require a single space or disallow whitespace after operators within attribute selectors.
  selector-attribute-operator-space-after: never

  # Require a single space or disallow whitespace before operators within attribute selectors.
  selector-attribute-operator-space-before: never

  # Require or disallow quotes for attribute values.
  selector-attribute-quotes: always

  # Require a single space or disallow whitespace after the combinators of selectors.
  selector-combinator-space-after: always

  # Require a single space or disallow whitespace before the combinators of selectors.
  selector-combinator-space-before: always

  # Disallow non-space characters for descendant combinators of selectors.
  selector-descendant-combinator-no-non-space: true

  # Require a newline or disallow whitespace after the commas of selector lists.
  selector-list-comma-newline-after: always

  # Require a newline or disallow whitespace before the commas of selector lists.
  selector-list-comma-newline-before: never-multi-line

  # Require a single space or disallow whitespace after the commas of selector lists.
  selector-list-comma-space-after: always-single-line

  # Require a single space or disallow whitespace before the commas of selector lists.
  selector-list-comma-space-before: never

  # Limit the number of attribute selectors in a selector.
  selector-max-attribute: 2

  # Limit the number of classes in a selector.
  selector-max-class: 4

  # Limit the number of combinators in a selector.
  selector-max-combinators: 3

  # Limit the number of compound selectors in a selector.
  selector-max-compound-selectors: 4

  # Limit the number of adjacent empty lines within selectors.
  selector-max-empty-lines: 0

  # Limit the number of id selectors in a selector.
  selector-max-id: 1

  # Limit the number of type in a selector.
  selector-max-type: 3

  # Limit the number of universal selectors in a selector.
  selector-max-universal: 1

  # Disallow vendor prefixes for selectors.
  selector-no-vendor-prefix: true

  # Specify lowercase or uppercase for pseudo-class selectors.
  selector-pseudo-class-case: lower

  # Disallow unknown pseudo-class selectors.
  selector-pseudo-class-no-unknown: true

  # Require a single space or disallow whitespace on the inside of the parentheses within pseudo-class selectors.
  selector-pseudo-class-parentheses-space-inside: never

  # Specify lowercase or uppercase for pseudo-element selectors.
  selector-pseudo-element-case: lower

  # Specify single or double colon notation for applicable pseudo-elements.
  selector-pseudo-element-colon-notation: double

  # Disallow unknown pseudo-element selectors.
  selector-pseudo-element-no-unknown: true

  # Specify lowercase or uppercase for type selector.
  selector-type-case: lower

  # Disallow unknown type selectors.
  selector-type-no-unknown: true

  # Disallow redundant values in shorthand properties.
  shorthand-property-no-redundant-values: true

  # Specify single or double quotes around strings.
  string-quotes: double

  # Disallow (unescaped) newlines in strings.
  string-no-newline: true

  # Specify the minimum number of milliseconds for time values.
  time-min-milliseconds: 100

  # Specify lowercase or uppercase for units.
  unit-case: lower

  # Disallow unknown units.
  unit-no-unknown: true

  # Require a newline or disallow whitespace after the commas of value lists.
  value-list-comma-newline-after: never-multi-line

  # Require a newline or disallow whitespace before the commas of value lists.
  value-list-comma-newline-before: never-multi-line

  # Require a single space or disallow whitespace after the commas of value lists.
  value-list-comma-space-after: always

  # Require a single space or disallow whitespace before the commas of value lists.
  value-list-comma-space-before: never

  # Limit the number of adjacent empty lines within value lists.
  value-list-max-empty-lines: 0

  # Disallow vendor prefixes for values.
  value-no-vendor-prefix: true


 # SMACSS-like property order rules (stylelint-order plugin).
  order/properties-order:

    # Box.

    - display
    - position
    - top
    - right
    - bottom
    - left

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - float
    - clear

    - resize

    - columns
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-count
    - column-width

    - grid-gap
    - grid-template-columns

    - animation
    - animation-name
    - animation-timing-function

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    # Border.

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background.

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    - fill

    - opacity

    # Text.

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Cursor.

    - cursor
    - pointer-events
    - user-select

    # Other.

    - appearance
    - border-collapse
    - border-spacing
    - box-shadow
    - box-sizing
    - caption-side
    - content
    - cursor
    - empty-cells
    - overflow
    - overflow-x
    - overflow-y
    - quotes
    - speak
    - table-layout
    - vertical-align
    - visibility
    - will-change
    - z-index


 # Additonal SCSS rules (stylelint-scss plugin).

  # Disallow `@extend` with missing placeholders.
  scss/at-extend-no-missing-placeholder: true

  # Since leading underscores are not needed, they can be omitted.
  scss/at-import-no-partial-leading-underscore: true

  # Disallow unknown at-rules. Should be used instead of stylelint's `at-rule-no-unknown`.
  scss/at-rule-no-unknown: true

  # Require a newline after the colon in `$`-variable declarations.
  scss/dollar-variable-colon-newline-after: always-multi-line

  # Require a single space or disallow whitespace before the colon in `$`-variable declarations.
  scss/dollar-variable-colon-space-before: never

  # Disallow Sass variables that are used without interpolation with CSS features that use custom identifiers.
  scss/dollar-variable-no-missing-interpolation: true

  # Disallow linebreaks after Sass operators.
  scss/operator-no-newline-after: true

  # Disallow linebreaks before Sass operators.
  scss/operator-no-newline-before: true

  # Disallow unspaced operators in Sass operations.
  scss/operator-no-unspaced: true

  # Disallow non-CSS `@import`s in partial files.
  scss/partial-no-import: true

  # Prevents unneeded nesting selectors.
  scss/selector-no-redundant-nesting-selector: true
